### ISSUE TITLE
Is there RxJava flatMap/merge equivalent in swave?

### ISSUE THREAD

**Issue by akarnokd** [sirthias/swave#22]
I'm trying to port some RxJava code to **swave** and I couldn't find an operator that takes a `Spout[Spout[T]]` and returns a `Spout[T]`, which is either `flatMap` for in-sequence and `merge` for out-of-sequence in RxJava. (Better yet, a `Spout[Iterable[T]] => Spout[T]` if available.) Disclaimer: I know practically nothing about Scala development.

I found `flattenConcat` which seems to compile in IntelliJ editor but then a run/build fails with `could not find implicit value for parameter ev: swave.core.Streamable[Long]{type Out = B} .flattenConcat()`, for example [here](https://github.com/akarnokd/akarnokd-misc-scala/blob/master/src/main/scala/ScrabbleWithSwave.scala#L116).

**Comment by sirthias** [comment]
@akarnokd *swave* is still under very heavy development at this point and the documentation at http://swave.io is currently coming together.
However, the documentation targets the current master branch which has already moved quite a bit forward since the last 0.5.0 release. There will be a fresh 0.6.0 release before the end of the month and the matching documentation will be done by then.

If you want to use the current state right now I'd recommend you clone the repository and `sbt publishLocal` a local snapshot build.

**Comment by sirthias** [comment]
And to answer your question: The current snapshot does include a `.flatMap(f)` transformation, which is simply a shorthand for `.map(f).flattenConcat()`.

**Comment by sirthias** [comment]
Also, I'd like to point you to the [mailing list](https://groups.google.com/group/swave-user/) or the [gitter channel](https://gitter.im/sirthias/swave), which works much better for support questions than this ticket system.
