### ISSUE TITLE
Implement a Drain.asyncParallelForeach

### ISSUE THREAD

**Issue by joost-de-vries** [sirthias/swave#27]
As a follow up from a discussion in `swave-user`: it would be superuseful to have a variant of Drain.foreach that accepts an async callback where the speed of completion of the async result provides backpressure.

Relevant quote from Mathias:
"We already have `Drain.parallelForeach` which is currently implemented like this: 
```scala
    def parallelForeach[T](parallelism: Int)(f: T ⇒ Unit)(implicit ec: ExecutionContext): Drain[T, Future[Unit]] = 
      Pipe[T].mapAsyncUnordered(parallelism)(x ⇒ Future(f(x))).to(Drain.ignore) 
```
We should change it to: 
```scala
    def parallelForeach[T](parallelism: Int)(f: T ⇒ Unit)(implicit ec: ExecutionContext): Drain[T, Future[Unit]] = 
      asyncParallelForeach(parallelism)(Future.apply) 

    def asyncParallelForeach[T](parallelism: Int)(f: T ⇒ Future[Unit])(implicit ec: ExecutionContext): Drain[T, Future[Unit]] = 
      Pipe[T].mapAsyncUnordered(parallelism)(f).to(Drain.ignore) 
```
"

**Comment by joost-de-vries** [comment]
This is super useful. I look forward to trying it out.
I was wondering about symmetry: would it be possible to have the opposite? A Spout that provides an async function and provides backpressure through how long the function takes to complete.

**Comment by sirthias** [comment]
Yes, that's absolutely possible. What would the signature look like?

**Comment by joost-de-vries** [comment]
@sirthias I guess something like this would be intuitive
```
trait SuperUsefulSpout[A]{
  def element(e:A):Future[Unit]
}
```

There's a wider them to this Sink and Spout: it seems that a large part of swave (documentation) is oriented towards streams that produce all their results at the moment of being ran.
That suits lightweight usage similar to using collections. Which is cool. But doesn't suit long running server processes whose utility starts after the run call has returned I think. 
Am I missing something there?

**Comment by sirthias** [comment]
No, I don't think you are missing anything.
There are probably more operators that swave could provide an async variant for, if needed.
If you see any opportunities here, please simply open tickets.

Your `SuperUsefulSpout` could be something like this then:

```scala
Spout.simplePush[A](bufferSize: Int = 1): A => Future[SimplePush.State]

object SimplePush {
  sealed trait State
  case object ReadyForNext extends State
  case object Cancelled extends State
}
```

The `bufferSize` would have to be > 0 in order to allow for the very first element to be pushed.
When the produced function is called even though the buffer is full the produced future would be completed with an error.
With a `bufferSize` > 1 you could even have "overlapping" production. The first Future would be already completed with `ReadyForNext` for example.
Of course, as a user one would have to be careful to never miss a future completion.

**Comment by joost-de-vries** [comment]
I wonder if it would be possible to have the speed with which the Future is completed communicate whether the downstream is keeping up. With a specified timeout for when the downstream is not keeping up at all. And an early error when the demand is much too much.
I guess that would involve some queueing mechanism on top of the primitives you suggest.
